# Runs on branches with a name like 'release/v{TAG}', tagging each commit with an incrementing release candidate
# like v{TAG}.rc-{n}


name: 'Build release candidate'
on:
  push:
    branches:
      - 'release/v*'
jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Calculate tag names'
        id: tags
        run: |
          releaseBranch=$(git branch --show-current | grep release/v*)
          branchTag=${releaseBranch#release/}
          sha=$(git rev-list --tags --max-count=1)
          echo "sha: $sha"
          [[ $sha == "" ]] && lastTag=NONE &&
          [[ $sha == "" ]] || lastTag="$(git describe --abbrev=0 --tags)"
          echo "::set-output name=previous::$lastTag"
          if [[ $lastTag =~ $branchTag-rc\.([0-9]*) ]]; then
              current="$branchTag.rc-$((BASH_REMATCH[1]+1))"
          else
              current="$branchTag-rc.1"
          fi
          echo $current
          echo "::set-output name=current::$current"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tags.outputs.current }}
          tag_prefix: ""

      - name: Enhance changelog
        id: changelog
        env:
          CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
        # Sample: Replace TT-73268 with a link to such tickets
        run: |
          newChangelog="$(echo "$CHANGELOG" |  sed "s/TT-\([0-9]*\)/[TT-\1](https:\/\/tickets.customer.com\/browse\/TT-\1)/g")"
          echo "$newChangelog" > release_changelog.md
          echo "::set-output name=enhanced::$newChangelog"
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ steps.tags.outputs.relTag }}
          name: ${{ steps.tags.outputs.relTag }}
          body_path: release_changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
