# When run on hotfix-branches like 'hotfix/v{TAG}', this pipeline and merges it into master and aims for prod deployment.

name: '🤚 🚨 Apply Hotfix'
on:
  workflow_dispatch:

jobs:
  hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Calculate tag names'
        id: tags
        run: |
          hotfixBranch=$(git branch --show-current | grep hotfix/v*)
          branchTag=${hotfixBranch#hotfix/}
          headTag=$(git describe --tags | grep "$branchTag")
          echo "::set-output name=preRelTag::$headTag"
          echo "::set-output name=hotfixBranch::$hotfixBranch"

      - name: Merge  -> master
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ steps.tags.outputs.hotfixBranch }}
          target-branch: master
          commit-message: "chore(release): ${{ steps.tags.outputs.relTag }}"
      - name: Delete hotfix branch
        env:
          branch: ${{ steps.tags.outputs.hotfixBranch }}
        run: |
          git push -d origin $branch
      - name: Create PR master --> develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          source_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_allow_empty: true
          pr_title: "Merge master into develop after hotfix ${{ steps.tags.outputs.headTag }}"
