# When run on release-branches like 'release/v{TAG}', this pipeline adds the tag v{TAG} without postfix to the head of
# the release branch, creates a github release with changelog from conventional commits and merges it into master.

name: '🤚 Create release'
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Calculate tag names'
        id: tags
        run: |
          releaseBranch=$(git branch --show-current | grep release/v*)
          branchTag=${releaseBranch#release/}
          headTag=$(git describe --tags | grep "$branchTag")
          echo "::set-output name=relTag::$branchTag"
          echo "::set-output name=preRelTag::$headTag"
          echo "::set-output name=releaseBranch::$releaseBranch"
      - name: Re-Tag docker image
        env:
          relTag: ${{ steps.tags.outputs.relTag }}
          preRelTag: ${{ steps.tags.outputs.preRelTag }}
        run: echo "Adding tag $relTag to image with tag $preRelTag"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tags.outputs.relTag }}
          tag_prefix: ""
      - name: Enhance changelog
        id: changelog
        env:
          CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
          JIRA_PROJECT: TT
          JIRA_HOST: tickets.customer.com
        run: |
          newChangelog="$(echo "$CHANGELOG" |  sed "s/$JIRA_PROJECT-\([0-9]*\)/[$JIRA_PROJECT-\1](https:\/\/$JIRA_HOST\/browse\/$JIRA_PROJECT-\1)/g")"
          echo "$newChangelog" > release_changelog.md
          echo "::set-output name=enhanced::$newChangelog"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tags.outputs.relTag }}
          name: ${{ steps.tags.outputs.relTag }}
          body_path: release_changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge  -> master
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ steps.tags.outputs.releaseBranch }}
          target-branch: master
          commit-message: "Release ${{ steps.tags.outputs.relTag }}"
      - name: Delete release branch
        env:
          branch: ${{ steps.tags.outputs.releaseBranch }}
        run: |
          git push -d origin $branch
      - name: Create PR master --> develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          source_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_allow_empty: true
          pr_title: "Merge master into develop after release ${{ steps.tags.outputs.relTag }}"
