name: "🤚 🚨 Stage branch for hotfix"

on:
  workflow_dispatch:

jobs:
  start-release-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display receiver
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Analyze repo
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          dry_run: true
          append_to_pre_release_tag: false
      - name: Determine hotfix branch name
        id: hotfix
        env:
          lastTag: ${{ steps.tag_version.outputs.previous_tag }}
        run: |
          mainVersion=${lastTag%-*}
          echo "::set-output name=branch-name::hotfix/$mainVersion"

      - name: Assert branch does not exist yet
        id: branch-exists
        env:
          branch: ${{ steps.hotfix.outputs.branch-name }}
        run: |
          branchExists=$(git ls-remote --heads origin ${branch})

          if [[ -z ${branchExists} ]]; then
              echo "::set-output name=exists::false"
          else
              echo "This hotfix does already exist"
              exit 1
          fi

      - uses: peterjgrainger/action-create-branch@v2.0.1
        if:  ${{ steps.branch-exists.outputs.exists == 'false' }}
        name: Create branch for release cycle
        env:
          # Use another token then GITHUB_TOKEN to trigger subsequent workflows
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
        with:
          branch: ${{ steps.hotfix.outputs.branch-name }}

