name: ⚙️ Test PR
on:
  pull_request_target:
    branches:
      - develop
      - master
      - release/v*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load workflow config
        run: cat .github/workflow-config.env >> $GITHUB_ENV
      - name: (TODO) Tests
        run: .github/scripts/test.sh
